TRANSPORT_TOOLS=[
 {'name':'athena_transport_pheromone_attention','description':'Freeze current Collective-V2 pheromone state for named routes into AOR/RAG attention-prior packets. This adapter never populates relevance, source_authority, evidence, confidence or Y authority.','inputSchema':{'type':'object','required':['route_keys'],'properties':{'route_keys':{'type':'array','minItems':1,'items':{'type':'string','minLength':1},'uniqueItems':True},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_alarm_to_gap','description':'Convert explicit alarmed nodes into GAP target/revalidation pressure while preserving alarm provenance. Alarm transport is not proof of falsity, causal dependence or logical entailment; missing residual metrics remain for measurement.','inputSchema':{'type':'object','required':['alarm_ref','alarm_nodes'],'properties':{'alarm_ref':{'type':'string','minLength':1},'alarm_nodes':{'type':'array','minItems':1,'items':{'type':'object','required':['node'],'properties':{'id':{'type':'string'},'node':{'type':'string','minLength':1},'severity':{'type':'number','minimum':0}},'additionalProperties':True}},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_aor_to_collective','description':'Translate a persisted AORRUN successor frontier into Collective task identities/capability requirements. Worker-allocation metrics are never invented; candidates lacking explicit collective_metrics remain UNMEASURED and are not allocation-ready.','inputSchema':{'type':'object','required':['run_id'],'properties':{'run_id':{'type':'string','minLength':1},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_rgo_to_reward','description':'Carry a witnessed observed RGO outcome into a reward-observation packet without automatically changing AOR DeltaJ/evidence/Y authority. If DeltaJ names the same outcome, a double-count guard is emitted.','inputSchema':{'type':'object','required':['outcome_ref','observed_rgo','witness_ref'],'properties':{'outcome_ref':{'type':'string','minLength':1},'observed_rgo':{'type':'number'},'witness_ref':{'type':'string','minLength':1},'delta_j':{'type':['number','null']},'delta_outcome_ref':{'type':['string','null']},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_bridge_to_collective','description':'Carry explicit bridge economics from an AOR bridge candidate into the Collective bridge-accounting packet. Economics are never derived from AOR bridge score.','inputSchema':{'type':'object','required':['candidate_ref','economics'],'properties':{'candidate_ref':{'type':'string','minLength':1},'economics':{'type':'object','required':['expected_future_uses','route_saving_per_use','quality_gain','resilience_gain','build_cost','maintenance_cost','locked_capacity_cost'],'properties':{name:{'type':'number','minimum':0} for name in ['expected_future_uses','route_saving_per_use','quality_gain','resilience_gain','build_cost','maintenance_cost','locked_capacity_cost']},'additionalProperties':False},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_antibody_to_repair','description':'Translate explicit failure-antibody matches into UNMEASURED FIELD repair candidates. A match never auto-executes or proves the repair will work; measurement and witnessed testing remain required.','inputSchema':{'type':'object','required':['failure_ref','matches'],'properties':{'failure_ref':{'type':'string','minLength':1},'matches':{'type':'array','items':{'type':'object','properties':{'antibody_id':{'type':'string'},'id':{'type':'string'},'repair':{},'target_ref':{'type':'string'},'score':{'type':'number'},'regression_refs':{'type':'array','items':{'type':'string'}}},'additionalProperties':True}},'actor':{'type':'string'},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_transport_get','description':'Fetch one persisted TRANSPORTRUN including frozen input/output boundary packet and digest.','inputSchema':{'type':'object','required':['run_id'],'properties':{'run_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_transport_replay','description':'Replay one persisted typed transport from its frozen inputs and verify transport digest. Replay proves adapter determinism, not semantic truth of the source organ.','inputSchema':{'type':'object','required':['run_id'],'properties':{'run_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_transport_recent','description':'List recent AOR×Collective transport receipts.','inputSchema':{'type':'object','properties':{'limit':{'type':'integer','minimum':1,'maximum':500}},'additionalProperties':False}},
]
TRANSPORT_TOOL_NAMES={tool['name'] for tool in TRANSPORT_TOOLS}
TRANSPORT_RESOURCE={'uri':'athena://aor-collective/transport','name':'AOR × Collective Typed Transport Fabric','mimeType':'application/json'}
