CANDIDATE_SCHEMA={'type':'object','properties':{'id':{'type':'string'},'oid':{'type':'string'},'cid':{'type':'string'},'name':{'type':'string'},'ref':{'type':'string'},'branch_id':{'type':'string'},'resolved':{'type':'boolean'},'requires':{'type':'array','items':{'type':'string'}},'readiness':{'type':'number'},'gain':{'type':'number'},'independence':{'type':'number'},'bridge':{'type':'number'},'cost':{'type':'number'},'resource_cost':{'type':'number'},'delta_j':{'type':'number'},'information_gain':{'type':'number'},'option_value':{'type':'number'},'evidence':{'type':'number'},'connection':{'type':'number'},'replay':{'type':'number'},'navigation':{'type':'number'},'reconstruction':{'type':'number'},'implementation':{'type':'number'},'novelty':{'type':'number'},'duplicate':{'type':['number','boolean']},'fake':{'type':['number','boolean']},'bloat':{'type':'number'},'unsupported':{'type':['number','boolean']},'unhandled_contradiction':{'type':['number','boolean']},'coordinate_loss':{'type':'number'},'test':{'type':'object'},'transaction':{'type':'object'},'coordinates':{'type':'object'},'require_coordinates':{'type':'boolean'}},'additionalProperties':True}
RESIDUAL_SCHEMA={'type':'object','properties':{'id':{'type':'string'},'name':{'type':'string'},'severity':{'type':'number'},'leverage':{'type':'number'},'information_gain':{'type':'number'},'cost':{'type':'number'}},'additionalProperties':True}
METRIC_SPEC_SCHEMA={'type':'object','required':['scale'],'properties':{'scale':{'type':'number'},'offset':{'type':'number'},'unit':{'type':'string'}},'additionalProperties':False}
METRIC_CONTRACT_SCHEMA={'type':'object','properties':{'basis_id':{'type':'string'},'strict':{'type':'boolean'},'metrics':{'type':'object','additionalProperties':METRIC_SPEC_SCHEMA}},'additionalProperties':False}
AOR_TOOLS=[
 {'name':'athena_orchestrate','description':'Compile and optionally persist AOR.3 decision state. UNKNOWN never becomes zero; dependency, evidence, test/persistence and calibration gates are fail-closed; scalar NEXT coexists with Pareto alternatives and explicit budget allocation.','inputSchema':{'type':'object','required':['seed'],'properties':{'seed':{},'candidates':{'type':'array','items':CANDIDATE_SCHEMA},'residuals':{'type':'array','items':RESIDUAL_SCHEMA},'budget':{'type':'object'},'metric_contract':METRIC_CONTRACT_SCHEMA,'actor':{'type':'string'},'task':{'type':'string'},'session_id':{'type':['string','null']},'persist':{'type':'boolean'}},'additionalProperties':False}},
 {'name':'athena_orchestration_get','description':'Fetch one persisted AORRUN with frozen input/output and decision digest.','inputSchema':{'type':'object','required':['run_id'],'properties':{'run_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_orchestration_replay','description':'Recompile one persisted AORRUN from frozen inputs and verify routing digest, NEXT, GROW and Pareto state.','inputSchema':{'type':'object','required':['run_id'],'properties':{'run_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_orchestration_recent','description':'List recent persisted AORRUN receipts.','inputSchema':{'type':'object','properties':{'limit':{'type':'integer','minimum':1,'maximum':200}},'additionalProperties':False}},
]
AOR_TOOL_NAMES={tool['name'] for tool in AOR_TOOLS}
AOR_RESOURCES=[
 {'uri':'athena://orchestration/law','name':'AOR Developmental Orchestration Law','mimeType':'application/json'},
 {'uri':'athena://orchestration/recent','name':'Recent AORRUN Receipts','mimeType':'application/json'},
]
