from __future__ import annotations

EVIDENCE_VERSION='BNMK.ADAPTER20.V2'

EVIDENCE_LAWS=[
    'USER_SEED != VERIFIED_EMPIRICAL',
    'REVIEW_SUMMARY != PRIMARY_WITNESS',
    'STRUCTURE != DYNAMICS',
    'IN_VITRO_RATE != UNIVERSAL_IN_VIVO_RATE',
    'MAXIMUM_REPORTED_RATE != TYPICAL_RATE',
    'BIOLOGICAL_HOMOLOGY != COMPUTATIONAL_ANALOGY',
    'ANALOGY != CAUSAL_EQUIVALENCE',
    'NUMERIC_VALUE_WITHOUT_CONDITIONS != CANONICAL_CONSTANT',
]

SOURCES={
'S01':{'title':'Direct observation of the rotation of F1-ATPase','journal':'Nature','year':1997,'doi':'10.1038/386299a0'},
'S02':{'title':'Rapid rotation of flagellar bundles in swimming bacteria','journal':'Nature','year':1987,'doi':'10.1038/325637a0'},
'S03':{'title':'Direct observation of kinesin stepping by optical trapping interferometry','journal':'Nature','year':1993,'doi':'10.1038/365721a0'},
'S04':{'title':'Single-Molecule Analysis of Dynein Processivity and Stepping Behavior','journal':'Cell','year':2006,'doi':'10.1016/j.cell.2006.05.046'},
'S05':{'title':'Single myosin molecule mechanics: piconewton forces and nanometre steps','journal':'Nature','year':1994,'doi':'10.1038/368113a0'},
'S06':{'title':'Following translation by single ribosomes one codon at a time','journal':'Nature','year':2008,'doi':'10.1038/nature06716'},
'S07':{'title':'Single-molecule studies of fork dynamics in Escherichia coli DNA replication','journal':'Nature Structural & Molecular Biology','year':2008,'doi':'10.1038/nsmb.1381'},
'S08':{'title':'Processive translocation and DNA unwinding by individual RecBCD enzyme molecules','journal':'Nature','year':2001,'doi':'10.1038/35053131'},
'S09':{'title':'Single-molecule analysis of DNA uncoiling by a type II topoisomerase','journal':'Nature','year':2000,'doi':'10.1038/35009144'},
'S10':{'title':'Reconstitution of the 26S proteasome reveals functional asymmetries in its AAA+ unfoldase','journal':'Nature Structural & Molecular Biology','year':2013,'doi':'10.1038/nsmb.2659'},
'S11':{'title':'Protein folding in the central cavity of the GroEL-GroES chaperonin complex','journal':'Nature','year':1996,'doi':'10.1038/379420a0'},
'S12':{'title':'Structure of a pathogenic type 3 secretion system in action','journal':'Nature Structural & Molecular Biology','year':2014,'doi':'10.1038/nsmb.2722'},
'S13':{'title':'Type VI secretion requires a dynamic contractile phage tail-like structure','journal':'Nature','year':2012,'doi':'10.1038/nature10846'},
'S14':{'title':'Three-dimensional rearrangement of proteins in the tail of bacteriophage T4 on infection of its host','journal':'Cell','year':2004,'doi':'10.1016/j.cell.2004.07.022'},
'S15':{'title':'Force and velocity measured for single molecules of RNA polymerase','journal':'Science','year':1998,'doi':'10.1126/science.282.5390.902'},
'S16':{'title':'Ordered and Dynamic Assembly of Single Spliceosomes','journal':'Science','year':2011,'doi':'10.1126/science.1198830'},
'S17':{'title':'Energy transduction and alternating access of the mammalian ABC transporter P-glycoprotein','journal':'Nature','year':2017,'doi':'10.1038/nature21414'},
'S18':{'title':'Sequence-directed DNA translocation by purified FtsK','journal':'Science','year':2005,'doi':'10.1126/science.1104885'},
'S19':{'title':'The bacteriophage phi29 portal motor can package DNA against a large internal force','journal':'Nature','year':2001,'doi':'10.1038/35099581'},
'S20':{'title':'DNA-loop extruding condensin complexes can traverse one another','journal':'Nature','year':2020,'doi':'10.1038/s41586-020-2067-5'},
}

ADAPTERS={
'ATP_SYNTHASE':{'adapter_id':'BNMK.A01.ATP_SYNTHASE','name':'ATP synthase','rows':[1],'source_id':'S01','role':'rotary chemo-mechanical transducer coupling ion-motive potential to ATP chemistry','cycle':['ION_OR_ATP_DRIVEN','ROTARY_STEP','CATALYTIC_COUPLING','PRODUCT_RELEASE'],'portable':['gradient_to_work','rotor_stator_coupling','reversible_transduction'],'athena':['pressure_to_execution','phase_coupled_work_conversion'],'original_seed':True},
'BACTERIAL_FLAGELLAR_MOTOR':{'adapter_id':'BNMK.A02.FLAGELLAR_MOTOR','name':'Bacterial flagellar motor','rows':[2],'source_id':'S02','role':'reversible rotary propulsion motor driving bacterial flagellar bundles','cycle':['PROTON_DRIVE','TORQUE_GENERATION','ROTATION','PROPULSION','REVERSE_OR_CONTINUE'],'portable':['distributed_rotary_drive','load_coupling','reversible_direction'],'athena':['distributed_actuation','direction_drive_action_separation'],'original_seed':True},
'KINESIN':{'adapter_id':'BNMK.A03.KINESIN','name':'Kinesin','rows':[3],'source_id':'S03','role':'processive microtubule motor for directed cargo transport','cycle':['BIND','STEP','ALTERNATE_CONTACT','ADVANCE','REPEAT_OR_RELEASE'],'portable':['typed_route_walking','processive_transport','cargo_bound_navigation'],'athena':['JSPACE_route_walking','packet_transport'],'original_seed':True},
'DYNEIN':{'adapter_id':'BNMK.A04.DYNEIN','name':'Cytoplasmic dynein','rows':[3],'source_id':'S04','role':'minus-end-directed processive microtubule motor','cycle':['BIND','STOCHASTIC_STEP','ADVANCE_OR_BACKSTEP','REPEAT_OR_RELEASE'],'portable':['stochastic_processive_walk','bidirectional_local_steps','two_motor_coordination'],'athena':['robust_route_walking','error_tolerant_transport'],'original_seed':True},
'MYOSIN':{'adapter_id':'BNMK.A05.MYOSIN','name':'Myosin','rows':[4],'source_id':'S05','role':'actin-coupled force-generating molecular motor','cycle':['ATTACH','POWER_STROKE','LOAD_RESPONSE','RELEASE','RESET'],'portable':['parallel_local_actuation','load_sharing','force_integration'],'athena':['collective_worker_actuation','load_aware_execution'],'original_seed':True},
'RIBOSOME':{'adapter_id':'BNMK.A06.RIBOSOME','name':'Ribosome','rows':[5],'source_id':'S06','role':'template-directed translation and polypeptide assembly machine','cycle':['PAUSE','DECODE','TRANSLOCATE_ONE_CODON','ASSEMBLE','REPEAT_OR_STOP'],'portable':['template_compiler','adapter_decode','sequential_assembly'],'athena':['spec_to_artifact_compilation','ordered_assembly'],'original_seed':True},
'DNA_POLYMERASE':{'adapter_id':'BNMK.A07.REPLISOME_POLIII','name':'E. coli Pol III replisome','rows':[6],'source_id':'S07','role':'template-directed DNA replication machine with coordinated helicase/primase coupling','cycle':['EXTEND','HELICASE_COUPLED_ADVANCE','PRIMASE_COORDINATION','CONTINUE_OR_PAUSE'],'portable':['copy_with_integrity','coupled_replication','processivity_coordination'],'athena':['state_replication','freshness_bound_copying'],'original_seed':True},
'HELICASE':{'adapter_id':'BNMK.A08.RECBCD','name':'RecBCD helicase/nuclease','rows':[7],'source_id':'S08','role':'processive dsDNA translocase/helicase-nuclease for recombinational repair','cycle':['BIND','TRANSLOCATE','UNWIND','PROCESS','CONTINUE_OR_TERMINATE'],'portable':['frontier_open','progressive_unzip','processive_translocation'],'athena':['recursive_source_mining','dependency_unzipping'],'original_seed':True},
'TOPOISOMERASE':{'adapter_id':'BNMK.A09.TOPOISOMERASE_II','name':'Type II DNA topoisomerase','rows':[8],'source_id':'S09','role':'ATP-dependent DNA topology editor','cycle':['CAPTURE','TRANSIENT_BREAK','STRAND_PASSAGE','RESEAL','VERIFY_TOPOLOGY'],'portable':['temporary_cut','topology_edit','rejoin_with_witness'],'athena':['branch_reconciliation','conflict_torsion_relief'],'original_seed':True},
'PROTEASOME':{'adapter_id':'BNMK.A10.PROTEASOME','name':'26S proteasome','rows':[9],'source_id':'S10','role':'ATP-dependent selective protein degradation machine','cycle':['ENGAGE','UNFOLD','TRANSLOCATE','PROTEOLYZE','RELEASE_FRAGMENTS'],'portable':['selective_degradation','gated_pruning','recycling_pipeline'],'athena':['artifact_lifecycle','cognitive_apoptosis'],'original_seed':True},
'GROEL_GROES_CHAPERONIN':{'adapter_id':'BNMK.A11.GROEL_GROES','name':'GroEL/GroES chaperonin','rows':[10],'source_id':'S11','role':'ATP-cycled protein folding cage','cycle':['CAPTURE','ENCAPSULATE','FOLDING_TRIAL','ATP_RELEASE','ACCEPT_OR_REBIND'],'portable':['sandboxed_repair','bounded_retry','refold_reverify'],'athena':['candidate_quarantine','repair_chamber'],'original_seed':True},
'TYPE_III_SECRETION_SYSTEM':{'adapter_id':'BNMK.A12.T3SS','name':'Type III secretion injectisome','rows':[11],'source_id':'S12','role':'membrane-spanning protein translocation nanomachine','cycle':['SUBSTRATE_ASSOCIATE','ENGAGE_UNFOLD','CHANNEL_TRANSLOCATE','EXIT'],'portable':['typed_boundary_channel','payload_gate','translocation_path'],'athena':['cross_lane_delivery','boundary_transport'],'original_seed':True},
'TYPE_VI_SECRETION_SYSTEM':{'adapter_id':'BNMK.A13.T6SS','name':'Type VI secretion system','rows':[12],'source_id':'S13','role':'dynamic contractile phage-tail-like secretion machine','cycle':['ASSEMBLE','RAPID_CONTRACTION','DISASSEMBLE','CLPV_REASSEMBLE'],'portable':['stored_energy_release','contractile_delivery','reset_by_recycling'],'athena':['commit_gated_execution','one_shot_delivery'],'original_seed':True},
'BACTERIOPHAGE_TAIL_ASSEMBLY':{'adapter_id':'BNMK.A14.T4_TAIL','name':'T4 bacteriophage contractile tail','rows':[12],'source_id':'S14','role':'host-attachment-triggered contractile penetration and genome-delivery apparatus','cycle':['ATTACH','BASEPLATE_SWITCH','SHEATH_CONTRACT','TUBE_PENETRATE','DNA_INJECT','SPENT'],'portable':['attachment_before_execution','contractile_injection','terminal_spent_state'],'athena':['commit_gated_delivery','one_shot_transaction'],'original_seed':True},
'RNA_POLYMERASE':{'adapter_id':'BNMK.A15.RNA_POLYMERASE','name':'E. coli RNA polymerase','rows':[3,5],'source_id':'S15','role':'processive DNA-track motor that synthesizes RNA from a DNA template','cycle':['SELECT_ADD_NTP','TRANSLOCATE','PAUSE_OR_BACKTRACK','REPEAT'],'portable':['template_track_motor','coupled_synthesis_translocation','load_sensitive_progress'],'athena':['stream_compilation','position_bound_generation'],'original_seed':False},
'SPLICEOSOME':{'adapter_id':'BNMK.A16.SPLICEOSOME','name':'Spliceosome','rows':[5],'source_id':'S16','role':'dynamic ribonucleoprotein assembly machine that removes introns from pre-mRNA','cycle':['ORDERED_ASSOCIATION','REVERSIBLE_INTERMEDIATE','RISING_COMMITMENT','FUNCTIONAL_ASSEMBLY'],'portable':['reversible_assembly','rising_commitment','ordered_subcomplex_admission'],'athena':['progressive_commit_protocol','reversible_pipeline_assembly'],'original_seed':False},
'ABC_TRANSPORTER':{'adapter_id':'BNMK.A17.ABC_TRANSPORTER','name':'P-glycoprotein ABC exporter','rows':[11],'source_id':'S17','role':'ATP-coupled alternating-access membrane exporter','cycle':['INWARD_FACING','SUBSTRATE_BOUND','ATP_TWO_STROKE','OUTWARD_FACING','RESET'],'portable':['alternating_access','energy_coupled_transport','two_stroke_gate'],'athena':['secure_boundary_adapter','two_sided_state_machine'],'original_seed':False},
'FTSK_TRANSLOCASE':{'adapter_id':'BNMK.A18.FTSK','name':'FtsK DNA translocase','rows':[3,7],'source_id':'S18','role':'fast ATP-powered sequence-directed DNA translocation motor','cycle':['LOAD_DNA','FAST_TRANSLOCATE','READ_DIRECTIONAL_CONTEXT','REVERSE_IF_REQUIRED','CONTINUE'],'portable':['sequence_directed_translocation','in_band_routing','local_reverse_without_detach'],'athena':['fast_graph_transport','route_correction'],'original_seed':False},
'PHI29_DNA_PACKAGING_MOTOR':{'adapter_id':'BNMK.A19.PHI29_PACKAGING','name':'Bacteriophage phi29 DNA packaging motor','rows':[3,11],'source_id':'S19','role':'ATP-driven portal motor packaging dsDNA into a confined capsid','cycle':['ENGAGE_DNA','ATP_PACKAGE','BACKPRESSURE_INCREASE','PAUSE_SLIP_RECOVER','CONTINUE_UNTIL_FILLED'],'portable':['backpressure_aware_transport','ring_motor_packaging','capacity_feedback'],'athena':['bounded_buffer_loading','congestion_control'],'original_seed':False},
'CONDENSIN':{'adapter_id':'BNMK.A20.CONDENSIN','name':'Yeast condensin','rows':[3,8],'source_id':'S20','role':'DNA-loop-extruding motor and chromosome-compaction organizer','cycle':['BIND','EXTRUDE_LOOP','MOTOR_ENCOUNTER','TRAVERSE_OR_RESIZE','CONTINUE'],'portable':['loop_extrusion','motor_traversal','collision_to_topology'],'athena':['dynamic_graph_compaction','conflict_traversal'],'original_seed':False},
}

QUANTITATIVE_CLAIMS=[
{'claim_id':'Q01','machine_id':'ATP_SYNTHASE','property':'rotary_torque','value':'>40','unit':'pN nm','qualifier':'greater than under high load','conditions':['single F1-ATPase','ATP-hydrolysis-driven rotation','high load'],'source_id':'S01'},
{'claim_id':'Q02','machine_id':'KINESIN','property':'step_size','value':8,'unit':'nm','qualifier':'resolved step size','conditions':['single kinesin','microtubule','controlled optical-trap load'],'source_id':'S03'},
{'claim_id':'Q03','machine_id':'DYNEIN','property':'most_frequent_step_size','value':8,'unit':'nm','qualifier':'most frequent; longer/lateral/back steps also observed','conditions':['recombinant S. cerevisiae dynein','single-molecule assay'],'source_id':'S04'},
{'claim_id':'Q04','machine_id':'MYOSIN','property':'low_load_step_displacement','value':11,'unit':'nm','qualifier':'average discrete step','conditions':['single myosin','single actin filament','low load'],'source_id':'S05'},
{'claim_id':'Q05','machine_id':'MYOSIN','property':'isometric_force_transient','value':'3-4','unit':'pN','qualifier':'average range','conditions':['single myosin','isometric in-vitro laser-trap assay'],'source_id':'S05'},
{'claim_id':'Q06','machine_id':'RIBOSOME','property':'translocation_step','value':3,'unit':'bases','qualifier':'one codon per measured translocation','conditions':['single ribosome','mRNA hairpin optical-tweezer assay'],'source_id':'S06'},
{'claim_id':'Q07','machine_id':'RIBOSOME','property':'translocation_time','value':'<0.1','unit':'s','qualifier':'less than','conditions':['single ribosome','mRNA hairpin assay','translocation excluding pause'],'source_id':'S06'},
{'claim_id':'Q08','machine_id':'DNA_POLYMERASE','property':'leading_strand_processivity','value':10.5,'unit':'kb','qualifier':'when Pol III coupled to DnaB','conditions':['E. coli Pol III','DnaB helicase','single-molecule leading-strand synthesis'],'source_id':'S07'},
{'claim_id':'Q09','machine_id':'HELICASE','property':'maximum_unwinding_rate','value':'972 +/- 172','unit':'bp/s','qualifier':'maximum reported','conditions':['individual RecBCD','single dsDNA'],'source_id':'S08'},
{'claim_id':'Q10','machine_id':'HELICASE','property':'maximum_processive_unwinding_length','value':42300,'unit':'bp','qualifier':'as many as reported for one molecule','conditions':['individual RecBCD','single-molecule dsDNA unwinding'],'source_id':'S08'},
{'claim_id':'Q11','machine_id':'TYPE_III_SECRETION_SYSTEM','property':'needle_length','value':'~800','unit':'Angstrom','qualifier':'approximate in studied injectisome','conditions':['Salmonella Typhimurium','structural T3SS study'],'source_id':'S12'},
{'claim_id':'Q12','machine_id':'FTSK_TRANSLOCASE','property':'translocation_speed','value':5,'unit':'kb/s','qualifier':'reported speed','conditions':['purified E. coli FtsK','single DNA molecules'],'source_id':'S18'},
{'claim_id':'Q13','machine_id':'FTSK_TRANSLOCASE','property':'opposing_force','value':'up to 60','unit':'pN','qualifier':'worked against forces up to','conditions':['purified E. coli FtsK','single-molecule DNA translocation'],'source_id':'S18'},
{'claim_id':'Q14','machine_id':'PHI29_DNA_PACKAGING_MOTOR','property':'opposing_load','value':'up to 57','unit':'pN','qualifier':'average loads up to','conditions':['phi29 DNA packaging','single-molecule optical tweezers'],'source_id':'S19'},
{'claim_id':'Q15','machine_id':'PHI29_DNA_PACKAGING_MOTOR','property':'estimated_internal_force_near_full_capsid','value':'~50','unit':'pN','qualifier':'inferred internal force as capsid fills','conditions':['phi29 packaging assay','rate decrease with filling'],'source_id':'S19'},
]
for _claim in QUANTITATIVE_CLAIMS:
    _claim['standing']='PRIMARY_CONDITIONED'
    _claim['universal_constant']=False

UNPROMOTED_USER_NUMERIC_CLAIMS=[
{'machine_id':'ATP_SYNTHASE','claim':'up to 9000 RPM','status':'UNVERIFIED_USER_SEED'},
{'machine_id':'BACTERIAL_FLAGELLAR_MOTOR','claim':'up to 100000 RPM','status':'UNVERIFIED_USER_SEED'},
{'machine_id':'DNA_POLYMERASE','claim':'up to 1000 bases/s','status':'UNVERIFIED_USER_SEED'},
]

ROW_FACETS={
1:{'identity_role':'rotary potential-to-work transducer','energy_drive':'ion-motive potential; isolated F1 can be ATP-hydrolysis driven','input_cargo':'ion flow plus nucleotide state','output_work':'rotary torque coupled to ATP chemistry','substrate_track':'membrane Fo coupled to F1 catalytic head','geometry_topology':'central rotor inside catalytic stator','state_cycle':'cyclic rotary catalytic conformations','coupling_gating':'ion/nucleotide state gates rotor transitions','fidelity_error_control':'productive coupling is state constrained','assembly_maintenance':'multi-subunit FoF1 assembly required','failure_recovery':'load changes/stalls rotation conditionally','interface_transfer':'pressure requires a lawful transducer before execution'},
2:{'identity_role':'reversible rotary propulsion motor','energy_drive':'protonmotive force/proton flux','input_cargo':'ion motive energy plus mechanical load','output_work':'rotation/torque/propulsion','substrate_track':'cell-envelope motor and external fluid load','geometry_topology':'basal rotary motor coupled to helical output','state_cycle':'torque generation -> rotation -> reverse/continue','coupling_gating':'load couples drive to speed/torque','fidelity_error_control':'direction control is distinct from torque generation','assembly_maintenance':'assembled motor/filament system','failure_recovery':'load response is conditioned, not one universal threshold','interface_transfer':'separate drive, direction selector and external actuation'},
3:{'identity_role':'processive addressed-track motor','energy_drive':'ATP or synthesis chemistry depending on adapter','input_cargo':'cargo/load/template/sequence/destination state','output_work':'directed advance, packaging, synthesis-coupled movement or loop extrusion','substrate_track':'microtubule or DNA/portal track','geometry_topology':'track-bound motor, dimer/ring/complex depending on adapter','state_cycle':'engage -> step/translocate -> context check -> repeat/reverse/release','coupling_gating':'polarity, sequence, load, capacity and collisions gate progress','fidelity_error_control':'local back/side steps or pauses need not violate global direction','assembly_maintenance':'machine architecture stays adapter-typed','failure_recovery':'detach/backtrack/pause/slip/collision can be recoverable','interface_transfer':'transport binds cargo, current address, direction and stop/release condition'},
4:{'identity_role':'local force-generating sliding actuator','energy_drive':'ATP-dependent mechanochemical cycle','input_cargo':'actin-bound load and motor state','output_work':'nanometre displacement and piconewton force','substrate_track':'actin filament','geometry_topology':'motor-actin contact composes into parallel arrays','state_cycle':'attach -> stroke -> load response -> release -> reset','coupling_gating':'load changes realized force/displacement','fidelity_error_control':'one local cycle is not the global contractile state','assembly_maintenance':'many local motors integrate into higher-order work','failure_recovery':'load sharing preserves collective output','interface_transfer':'large actions decompose into bounded witnessed local actuators'},
5:{'identity_role':'template/information-processing assembler','energy_drive':'nucleotide chemistry/factor cycles, adapter specific','input_cargo':'template, substrates or staged RNP subcomplexes','output_work':'polymer assembly or progressively committed processing machine','substrate_track':'nucleic-acid template/pre-mRNA','geometry_topology':'machine remains position-bound while components enter/leave/advance','state_cycle':'recognize -> admit -> transform/assemble -> advance/commit','coupling_gating':'template/stage/commitment controls legal next transition','fidelity_error_control':'decode/proofread/abort stays distinct from forward progress','assembly_maintenance':'assembly may itself be the computational cycle','failure_recovery':'pause/backtrack/reversible dissociation preserves options','interface_transfer':'spec -> position-aware decode -> ordered admission with staged reversibility'},
6:{'identity_role':'template-directed coupled replication machine','energy_drive':'polymerization plus ATP-driven helicase activity','input_cargo':'DNA template/primer/nucleotides/replisome factors','output_work':'leading-strand synthesis with fork progression','substrate_track':'moving DNA replication fork','geometry_topology':'polymerase coupled to helicase/primase','state_cycle':'extend -> advance -> coordinate -> continue/pause','coupling_gating':'partner interactions gate processivity/coordination','fidelity_error_control':'proofreading remains distinct from processivity evidence','assembly_maintenance':'functional replication is a multi-protein replisome property','failure_recovery':'processivity loss requires restart/repair, not silent continuation','interface_transfer':'copy exact current source/version; perfect stale copying is failure'},
7:{'identity_role':'high-processivity polymer frontier translocase','energy_drive':'ATP hydrolysis','input_cargo':'long dsDNA plus sequence/context','output_work':'unwinding/processing or long-range translocation','substrate_track':'DNA is track and information-bearing substrate','geometry_topology':'motor stays engaged as local frontier moves','state_cycle':'bind/load -> translocate -> expose/read context -> continue/reverse/stop','coupling_gating':'ATP and sequence context can change progress/direction','fidelity_error_control':'route correction can occur without dropping engagement','assembly_maintenance':'motor complex must remain processive','failure_recovery':'local reversal/restart beats pretending frontier completion','interface_transfer':'open only next required dependency/source frontier and preserve return path'},
8:{'identity_role':'polymer topology-changing machine','energy_drive':'ATP-dependent topology cycles','input_cargo':'entangled/supercoiled DNA or loop structure','output_work':'strand passage/relaxation or loop extrusion/restructuring','substrate_track':'DNA topology/geometry','geometry_topology':'transient strand gate or loop-extruding motor','state_cycle':'engage stress -> bounded edit/extrude -> encounter/check -> reseal/continue','coupling_gating':'controlled gate/collision/loop constraints','fidelity_error_control':'continuity/ancestry preserved across topology edits','assembly_maintenance':'topology structures can assemble/dissolve dynamically','failure_recovery':'reseal or traverse collision instead of deadlock','interface_transfer':'treat branch/JSPACE conflict as topology, not flat text disagreement'},
9:{'identity_role':'selective ATP-dependent degradation machine','energy_drive':'AAA+ ATPase hydrolysis','input_cargo':'selected protein substrate','output_work':'unfolding/translocation/proteolysis/recyclable fragments','substrate_track':'substrate mechanically fed to proteolytic core','geometry_topology':'heterohexameric unfoldase coupled to degradation chamber','state_cycle':'engage -> unfold -> translocate -> proteolyze -> release','coupling_gating':'recognition/admission and ATPase state gate destruction','fidelity_error_control':'weak narrative tag cannot authorize degradation','assembly_maintenance':'intact unfoldase/core complex required','failure_recovery':'partial failure holds rather than erases lineage','interface_transfer':'prune active routing after typed gate; preserve provenance/recycle fragments'},
10:{'identity_role':'isolated retry/refolding chamber','energy_drive':'ATP-dependent cap/release cycle','input_cargo':'non-native client protein','output_work':'native/committed fold or another retry','substrate_track':'client is transformed inside cavity','geometry_topology':'GroES-capped GroEL ring forms enclosed cage','state_cycle':'capture -> encapsulate -> trial -> release -> accept/rebind','coupling_gating':'cap state isolates; ATP state releases','fidelity_error_control':'incomplete fold can rebind instead of false acceptance','assembly_maintenance':'repair chamber is reused across cycles','failure_recovery':'failure becomes another bounded trial','interface_transfer':'quarantine malformed candidate; reintroduce only after renewed verification'},
11:{'identity_role':'gated boundary-crossing transport machine','energy_drive':'secretion/ATP/packaging work depending on adapter','input_cargo':'protein substrate, membrane substrate or viral DNA','output_work':'translocation across a boundary or into bounded destination','substrate_track':'membrane/conduit/portal interface','geometry_topology':'needle channel, alternating-access domain or portal','state_cycle':'recognize -> gate/access transition -> translocate -> exit/fill -> reset/stop','coupling_gating':'payload compatibility, ATP/substrate state and backpressure','fidelity_error_control':'route != interface match != delivery != consumption','assembly_maintenance':'aligned conduit/transport complex required before commitment','failure_recovery':'blocked/wrong conformation/saturation -> HOLD/retry','interface_transfer':'typed producer/consumer contracts plus delivery receipts and backpressure'},
12:{'identity_role':'stored-energy contractile delivery machine','energy_drive':'metastable sheath/conformation; T6SS uses ATP remodelling for reset','input_cargo':'ready extended sheath/tube plus target/payload context','output_work':'rapid contraction, penetration/secretion and payload delivery','substrate_track':'target envelope and baseplate/anchor interface','geometry_topology':'contractile sheath surrounds penetrating tube','state_cycle':'assemble/search -> attach/ready -> fire -> deliver -> reset/spent','coupling_gating':'attachment/readiness precedes stored-energy release','fidelity_error_control':'aim/attachment/delivery/downstream effect remain distinct','assembly_maintenance':'T6SS recycles; T4 mature tail is preassembled/metastable','failure_recovery':'reusable reset vs one-shot spent state must be explicit','interface_transfer':'current attachment -> arm -> commit -> delivery witness -> terminal/reset'},
}

OPERATOR_PHYLOGENY={
'ENERGY_TRANSDUCERS':['ATP_SYNTHASE','BACTERIAL_FLAGELLAR_MOTOR','ABC_TRANSPORTER'],
'TRACK_AND_POLYMER_MOTORS':['KINESIN','DYNEIN','MYOSIN','RNA_POLYMERASE','FTSK_TRANSLOCASE','PHI29_DNA_PACKAGING_MOTOR','CONDENSIN'],
'TEMPLATE_INFORMATION_MACHINES':['RIBOSOME','DNA_POLYMERASE','RNA_POLYMERASE','SPLICEOSOME'],
'TOPOLOGY_MACHINES':['HELICASE','TOPOISOMERASE','FTSK_TRANSLOCASE','CONDENSIN'],
'PROTEOSTASIS':['PROTEASOME','GROEL_GROES_CHAPERONIN'],
'BOUNDARY_DELIVERY':['ABC_TRANSPORTER','TYPE_III_SECRETION_SYSTEM','TYPE_VI_SECRETION_SYSTEM','BACTERIOPHAGE_TAIL_ASSEMBLY','PHI29_DNA_PACKAGING_MOTOR'],
}

SECOND_ORDER_OPERATORS=[
'ATTACH_GATE_COMMIT','PROCESSIVE_CARGO_WALK','REVERSIBLE_ASSEMBLY_WITH_RISING_COMMITMENT','ALTERNATING_ACCESS_TRANSPORT','RING_MOTOR_WITH_BACKPRESSURE','LOOP_EXTRUSION_TOPOLOGY_CONTROL','UNFOLD_TRANSLOCATE_DEGRADE','CAPTURE_ISOLATE_REFOLD_RELEASE','CUT_PASS_RESEAL','TEMPLATE_READ_ASSEMBLE_ADVANCE','SEQUENCE_DIRECTED_ROUTE_REVERSAL','COLLISION_TRAVERSE_INSTEAD_OF_DEADLOCK'
]
