from __future__ import annotations

COLLECTIVE_GROWTH_TOOLS = [
    {"name":"athena_collective_allocate","description":"Allocate tasks by demand × capability fit × available capacity rather than equal participation.","inputSchema":{"type":"object","required":["tasks","workers"],"properties":{"tasks":{"type":"array","minItems":1,"maxItems":256,"items":{"type":"object","properties":{"id":{"type":"string"},"utility":{"type":"number","minimum":0,"maximum":1},"gap":{"type":"number","minimum":0,"maximum":1},"bridge_value":{"type":"number","minimum":0,"maximum":1},"saturation":{"type":"number","minimum":0,"maximum":1},"urgency":{"type":"number","minimum":0,"maximum":1},"required_capabilities":{"type":"array","items":{"type":"string"}}},"additionalProperties":False}},"workers":{"type":"array","minItems":1,"maxItems":256,"items":{"type":"object","properties":{"id":{"type":"string"},"capabilities":{"type":"array","items":{"type":"string"}},"load":{"type":"number","minimum":0,"maximum":1}},"additionalProperties":False}},"max_assignments_per_worker":{"type":"integer","minimum":1,"maximum":16},"alpha":{"type":"number","minimum":0},"beta":{"type":"number","minimum":0}},"additionalProperties":False}},
    {"name":"athena_bridge_account","description":"Apply living-bridge cost accounting: build only when future routing/reuse/quality/resilience value exceeds build, maintenance and locked-capacity cost.","inputSchema":{"type":"object","required":["bridge"],"properties":{"bridge":{"type":"object","properties":{"expected_future_uses":{"type":"number","minimum":0},"route_saving_per_use":{"type":"number","minimum":0},"quality_gain":{"type":"number","minimum":0},"resilience_gain":{"type":"number","minimum":0},"build_cost":{"type":"number","minimum":0},"maintenance_cost":{"type":"number","minimum":0},"locked_capacity_cost":{"type":"number","minimum":0}},"additionalProperties":False}},"additionalProperties":False}},
    {"name":"athena_collective_restructure","description":"Choose FISSION/FUSE/HOLD from coordination pressure, contagion, cohesion, complementarity, duplicate work, shared dependencies and identity conflict.","inputSchema":{"type":"object","required":["metrics"],"properties":{"metrics":{"type":"object","properties":{"coordination_overhead":{"type":"number","minimum":0,"maximum":1},"contagion":{"type":"number","minimum":0,"maximum":1},"size_pressure":{"type":"number","minimum":0,"maximum":1},"internal_cohesion":{"type":"number","minimum":0,"maximum":1},"complementarity":{"type":"number","minimum":0,"maximum":1},"duplicate_work":{"type":"number","minimum":0,"maximum":1},"shared_dependencies":{"type":"number","minimum":0,"maximum":1},"interface_maturity":{"type":"number","minimum":0,"maximum":1},"identity_conflict":{"type":"number","minimum":0,"maximum":1}},"additionalProperties":False}},"additionalProperties":False}},
    {"name":"athena_dependency_alarm","description":"Propagate a failure/change alarm only over explicit influence/dependency edges with weight, hop decay, threshold and bounded radius.","inputSchema":{"type":"object","required":["seeds","edges"],"properties":{"seeds":{"type":"array","minItems":1,"maxItems":128,"items":{"type":"object","required":["node"],"properties":{"node":{"type":"string"},"severity":{"type":"number","minimum":0,"maximum":1}},"additionalProperties":False}},"edges":{"type":"array","maxItems":4096,"items":{"type":"object","required":["src","dst"],"properties":{"src":{"type":"string"},"dst":{"type":"string"},"weight":{"type":"number","minimum":0,"maximum":1},"relation":{"type":"string"}},"additionalProperties":False}},"max_hops":{"type":"integer","minimum":0,"maximum":64},"hop_decay":{"type":"number","minimum":0,"maximum":1},"threshold":{"type":"number","minimum":0,"maximum":1}},"additionalProperties":False}},
    {"name":"athena_artifact_lifecycle","description":"Assign KEEP_ACTIVE/KEEP_REFERENCE/DORMANT/QUARANTINE/PRUNE_REFERENCE while preserving lineage and downstream dependencies.","inputSchema":{"type":"object","required":["artifacts"],"properties":{"artifacts":{"type":"array","minItems":1,"maxItems":1024,"items":{"type":"object","properties":{"id":{"type":"string"},"reuse":{"type":"number","minimum":0,"maximum":1},"novelty":{"type":"number","minimum":0,"maximum":1},"evidence":{"type":"number","minimum":0,"maximum":1},"age":{"type":"number","minimum":0,"maximum":1},"superseded":{"type":"boolean"},"downstream_dependents":{"type":"integer","minimum":0},"critical_lineage":{"type":"boolean"}},"additionalProperties":False}}},"additionalProperties":False}}
]
