from __future__ import annotations
from typing import Any

COORDINATION_INVENTORY_VERSION='ATHENA.ORGAN.INVENTORY.1.1'
PARTY_REWARD_VERSION='PARTY.REWARD.PROVENANCE.3.2'

def _o(id,version,cls,authority,layer,tools=(),resources=(),tests=(),sources=(),specs=(),laws=()):return {'id':id,'version':version,'integration_class':cls,'authority_plane':authority,'manifest_layer':layer,'omega_key':'coordination','tools':list(tools),'resources':list(resources),'critical_tests':list(tests),'source_refs':list(sources),'spec_refs':list(specs),'laws':list(laws)}

MATURE_ORGANS=(
 _o('MESSAGE_BOARD_V1','ATHENA.MESSAGE.BOARD.V1','PROMPT_RUNTIME_PUBLIC','COORDINATION_PRESENCE_CLAIM_MESSAGE','MESSAGE_BOARD_V1',['athena_message_board'],(),['tests/test_message_board.py','tests/test_message_board_registration.py','tests/test_agent_bootstrap_message_board.py'],['athena_mcp/message_board.py','athena_mcp/agent_bootstrap_message_board.py','athena_mcp/agent_bootstrap_message_board_activation.py'],['spec/AGENT_BOOT_MESSAGE_BOARD_V1.json'],['MESSAGE_BOARD = SOLE_PRESENCE_CLAIM_MESSAGE_AUTHORITY','MESSAGE_BOARD != Y1_CANONICAL_SEMANTIC_AUTHORITY','BOARD_STATE != EXECUTION_AUTHORITY != WORLD_TRUTH']),
 _o('COHESION_MESH_V1','COHESION.MESH.MATCHMAKING.1','PUBLIC_GIT_BACKED_LAZY','ADVISORY_COORDINATION','COHESION_MESH_V1',['athena_cohesion_request_offer','athena_cohesion_matchmake','athena_cohesion_coalition','athena_cohesion_solo_party_compare'],['athena://cohesion/v1'],['tests/test_cohesion_matchmaking.py'],['athena_mcp/cohesion_mesh.py','athena_mcp/cohesion_matchmaking.py','athena_mcp/cohesion_mesh_protocol.py'],(),['COHESION != CLAIM_AUTHORITY','COHESION != ASSIGNMENT_AUTHORITY','COHESION != EXECUTION_AUTHORITY']),
 _o('COHESION_DUPLICATE_GUARD_V1','COHESION.DUPLICATE.GUARD.1','PUBLIC_READ_ONLY_MEMBRANE','READ_ONLY_STEERING','COHESION_DUPLICATE_GUARD_V1',['athena_cohesion_duplicate_guard'],(),['tests/test_cohesion_duplicate_guard.py'],['athena_mcp/cohesion_duplicate_guard.py','athena_mcp/cohesion_duplicate_guard_protocol.py'],['spec/COHESION_DUPLICATE_GUARD_V1.json'],['FUZZY_SIMILARITY != DUPLICATE_PROOF','TREATMENT_OPTION != TREATMENT_EXECUTION']),
 _o('COHESION_EVIDENCE_GUARD_V1','ATHENA.COHESION.EVIDENCE.GUARD.V1','INTERNAL_FAIL_CLOSED_MEMBRANE','EVIDENCE_COVERAGE_ONLY','COHESION_EVIDENCE_GUARD_V1',(),(),['tests/test_cohesion_evidence_guard.py'],['athena_mcp/cohesion_evidence_guard.py'],(),['PARTIAL_MATCHED_SUBSET_OR_REUSED_EVIDENCE != SUFFICIENT_COMPARATIVE_EVIDENCE','CAUSAL_EFFECT = UNKNOWN','PROMOTION_AUTHORITY = FALSE']),
 _o('AGENT_BOOT_COHESION_TREATMENT_V1','ATHENA.AGENT.BOOT.COHESION.TREATMENT.V1','BOOTSTRAP_ONLY_READ_ONLY_PROJECTION','BOOTSTRAP_STEERING','AGENT_BOOT_COHESION_TREATMENT_V1',(),(),['tests/test_agent_bootstrap_cohesion_treatment.py'],['athena_mcp/agent_bootstrap_cohesion_treatment.py'],['spec/AGENT_BOOT_COHESION_TREATMENT_V1.json'],['BOOT_HOLD != TREATMENT_EXECUTION','TREATMENT_PROJECTION != CLAIM_MUTATION']),
 _o('PARTY_COORDINATION_V1','ATHENA.PARTY.COORDINATION.V1','PUBLIC_GIT_BACKED_COORDINATION','PARTY_STATE_AND_REWARD_CANDIDATE','PARTY_COORDINATION_V1',['athena_party_form','athena_party_join','athena_party_state','athena_party_list','athena_party_observe'],['athena://party-coordination/v1'],['tests/test_party_coordination.py'],['athena_mcp/party_coordination.py','athena_mcp/party_coordination_protocol.py'],(),['PARTY_COORDINATION != GLOBAL_XP_AUTHORITY','PARTY_OBSERVATION != RESULT_TRUTH']),
 _o('PARTY_CHANNEL_V2','ATHENA.PARTY.CHANNEL.V2','PUBLIC_MESSAGE_BOARD_TRANSPORT','PARTY_SCOPED_COMMUNICATION','PARTY_CHANNEL_V2',['athena_party_message'],(),['tests/test_party_coordination.py'],['athena_mcp/party_coordination_v2.py','athena_mcp/party_coordination_v2_protocol.py'],(),['PARTY_CHANNEL_TRANSPORT = MESSAGE_BOARD_V1','MESSAGE_POST != XP_AWARD']),
 _o('PARTY_REWARD_PROVENANCE_V3_2',PARTY_REWARD_VERSION,'PUBLIC_PROVENANCE_AND_NUMERIC_MEMBRANE','PARTY_REWARD_PROVENANCE_ONLY','PARTY_REWARD_PROVENANCE_V3_2',['athena_party_result'],(),['tests/test_party_reward_provenance.py','tests/test_party_reward_v3_1.py','tests/test_party_reward_v3_2.py'],['athena_mcp/party_coordination_v3.py','athena_mcp/party_coordination_v3_1.py','athena_mcp/party_coordination_v3_2.py','athena_mcp/party_coordination_v3_protocol.py'],(),['PARTY_RESULT != RESULT_TRUTH','PARTY_RESULT != GLOBAL_XP_AUTHORITY','V3_PACKET_VERSION_REQUIRED','INNER_RESULT_VERIFY_MUST_MATCH_OUTER_MESSAGE_BOARD_ROLE','BASE_XP_MUST_BE_FINITE_NON_BOOLEAN_BEFORE_PARTY_REWARD_PROCESSING','FINITE_NUMERIC_VALIDATION != UPSTREAM_XP_VERIFICATION_OR_MINT_AUTHORITY']),
)

def mature_organs():return tuple(dict(x) for x in MATURE_ORGANS)
def inventory_manifest():return {'version':COORDINATION_INVENTORY_VERSION,'organs':[dict(x) for x in MATURE_ORGANS],'party_reward_current':PARTY_REWARD_VERSION,'law':'maturity is explicit; Message Board coordination authority remains distinct from Y1 semantic authority; Party V3.2 is the active reward-provenance membrane'}
