CYCLE_TOOLS=[
 {'name':'athena_cycle_start','description':'Start a persisted ATHENA.CYCLE.1 whole-organism run from a task seed and explicit phase configuration. Starting creates state only; it does not claim later semantic phases executed.','inputSchema':{'type':'object','required':['task_ref','seed'],'properties':{'task_ref':{'type':'string','minLength':1},'seed':{},'config':{'type':'object'},'actor':{'type':'string'}},'additionalProperties':False}},
 {'name':'athena_cycle_advance','description':'Advance a CYCLE.1 through as many real internal phases as possible, merging newly supplied witnessed inputs. Semantic boundaries stop with typed WAITING_* state instead of simulating measurements, execution or tests.','inputSchema':{'type':'object','required':['cycle_id'],'properties':{'cycle_id':{'type':'string','minLength':1},'inputs':{'type':'object'},'max_steps':{'type':'integer','minimum':1,'maximum':64}},'additionalProperties':False}},
 {'name':'athena_cycle_state','description':'Fetch one persisted CYCLE.1 state, phase artifacts, wait requirements, public phase-event receipts and RETURN state.','inputSchema':{'type':'object','required':['cycle_id'],'properties':{'cycle_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_cycle_replay','description':'Verify the stored cycle state digest and deterministic replay/integrity receipts of persisted RAG/HUG-packet/GAP/FIELD/AOR/transport child runs. External semantic execution/test truth is not re-simulated.','inputSchema':{'type':'object','required':['cycle_id'],'properties':{'cycle_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_cycle_recent','description':'List recent CYCLE.1 runs and typed ACTIVE/WAITING/COMPLETE status without expanding full state.','inputSchema':{'type':'object','properties':{'limit':{'type':'integer','minimum':1,'maximum':500}},'additionalProperties':False}},
]
CYCLE_TOOL_NAMES={tool['name'] for tool in CYCLE_TOOLS}
CYCLE_RESOURCE={'uri':'athena://cycle','name':'ATHENA.CYCLE.1 Resumable Whole-Organism Runtime','mimeType':'application/json'}
