from __future__ import annotations

AID={"type":"string","minLength":1,"maxLength":256}
TTL={"type":"integer","minimum":250,"maximum":300000}
LAMPORT={"type":"integer","minimum":0}
PARENTS={"type":"array","maxItems":32,"items":{"type":"string","minLength":1},"uniqueItems":True}

EPHEMERAL_COORDINATION_TOOLS=[
 {"name":"athena_ephemeral_present","description":"Publish expiring process-local coordination presence. Presence is advisory and is not a claim, host-liveness proof, or durable truth.","inputSchema":{"type":"object","required":["aid","epoch","ttl_ms","capabilities","need_offer_summary","lamport","causal_parents","source_digest"],"properties":{"aid":AID,"epoch":{"type":"string","minLength":1,"maxLength":256},"ttl_ms":TTL,"capabilities":{"type":"array","maxItems":64,"items":{"type":"string","minLength":1},"uniqueItems":True},"need_offer_summary":{"type":"object"},"lamport":LAMPORT,"causal_parents":PARENTS,"source_digest":{"type":"string","minLength":1,"maxLength":512}},"additionalProperties":False}},
 {"name":"athena_ephemeral_post","description":"Route a bounded TTL packet to explicit AIDs in the process-local fast plane. No broadcast, consumption, durable promotion, or push delivery is implied.","inputSchema":{"type":"object","required":["sender_aid","recipient_selector","delivery_class","salience","ttl_ms","packet_digest_or_ref","lamport","causal_parents"],"properties":{"sender_aid":AID,"recipient_selector":{"type":"object","required":["aids"],"properties":{"aids":{"type":"array","minItems":1,"maxItems":32,"items":AID,"uniqueItems":True}},"additionalProperties":False},"delivery_class":{"type":"string","enum":["RENDEZVOUS","NEED_OFFER","NUDGE","BLOCKER","MATERIAL_CANDIDATE"]},"salience":{"type":"number","minimum":0,"maximum":1},"ttl_ms":TTL,"packet_digest_or_ref":{"type":"string","minLength":1,"maxLength":1024},"lamport":LAMPORT,"causal_parents":PARENTS},"additionalProperties":False}},
 {"name":"athena_ephemeral_poll","description":"Explicitly poll one AID's bounded TTL queue after a monotonic process cursor. Polling is foreground runtime work, not hidden background execution.","inputSchema":{"type":"object","required":["aid"],"properties":{"aid":AID,"after_cursor":{"type":"integer","minimum":0},"max_items":{"type":"integer","minimum":1,"maximum":100},"salience_budget":{"type":"number","minimum":0,"maximum":32}},"additionalProperties":False}},
 {"name":"athena_ephemeral_receipt","description":"Record one monotonic caller-attested delivery/consumption stage for a routed packet. Receipt stages do not mint causal gain or durable authority.","inputSchema":{"type":"object","required":["packet_id","aid","stage"],"properties":{"packet_id":{"type":"string","minLength":1,"maxLength":128},"aid":AID,"stage":{"type":"string","enum":["DELIVERED","PRESENTED","CONSUMED","INCORPORATED","DECISION_CHANGED"]},"witness":{"type":"object"}},"additionalProperties":False}},
 {"name":"athena_ephemeral_snapshot","description":"Read an advisory expiring snapshot of process-local presence, need/offer summaries, and queue pressure. Snapshot authority is NONE.","inputSchema":{"type":"object","properties":{"scope":{"type":"string","minLength":1,"maxLength":320},"freshness_bound_ms":TTL},"additionalProperties":False}}
]
EPHEMERAL_COORDINATION_TOOL_NAMES={tool["name"] for tool in EPHEMERAL_COORDINATION_TOOLS}
EPHEMERAL_COORDINATION_RESOURCE={"uri":"athena://coordination/ephemeral/v0","name":"ATHENA Ephemeral Coordination Membrane V0","mimeType":"application/json"}
