from __future__ import annotations

from .orchestration_retrieval.specs import RETRIEVAL_ROLES

MEASUREMENT_SCHEMA={"type":"object","required":["value","method","witness_ref"],"properties":{"value":{"type":"number","minimum":0,"maximum":1},"method":{"type":"string","minLength":1},"witness_ref":{"type":"string","minLength":1}},"additionalProperties":True}
# Presence of a retrieval metric is deliberately NOT required by JSON schema.
# When a packet is present it must be witnessed and well-formed; when absent the
# compiler types the operand UNKNOWN and emits measurement_plan instead of
# treating absence as zero or rejecting the request before RAG.1 can reason.
CANDIDATE_SCHEMA={"type":"object","properties":{"id":{"type":"string"},"oid":{"type":"string"},"cid":{"type":"string"},"ref":{"type":"string"},"source_ref":{"type":"string"},"measurements":{"type":"object","properties":{"relevance":MEASUREMENT_SCHEMA,"source_authority":MEASUREMENT_SCHEMA,"cross_value":MEASUREMENT_SCHEMA,"decision_relevance":MEASUREMENT_SCHEMA},"additionalProperties":True},"source_time":{"type":"number"},"timeless":{"type":"boolean"},"cost":{"type":"number","exclusiveMinimum":0},"roles":{"type":"array","items":{"enum":list(RETRIEVAL_ROLES)},"uniqueItems":True},"facets":{"type":"array","items":{"type":"string"},"uniqueItems":True},"coordinate_keys":{"type":"array","items":{"type":"string"},"uniqueItems":True},"lineage_keys":{"type":"array","items":{"type":"string"},"uniqueItems":True}},"required":["measurements","cost"],"additionalProperties":True}
QUERY_SCHEMA={"type":"object","required":["as_of","freshness_half_life"],"properties":{"as_of":{"type":"number"},"freshness_half_life":{"type":"number","exclusiveMinimum":0},"budget":{"type":"number","minimum":0},"max_items":{"type":"integer","minimum":0},"required_roles":{"type":"array","items":{"enum":list(RETRIEVAL_ROLES)},"uniqueItems":True},"required_facets":{"type":"array","items":{"type":"string"},"uniqueItems":True},"preferred_coordinates":{"type":"array","items":{"type":"string"},"uniqueItems":True},"preferred_lineages":{"type":"array","items":{"type":"string"},"uniqueItems":True},"role_coverage_weight":{"type":"number","minimum":0},"facet_coverage_weight":{"type":"number","minimum":0}},"additionalProperties":True}

RETRIEVAL_TOOLS=[
{"name":"athena_retrieval_compile","description":"Compile and optionally persist a RAG.1 retrieval decision over supplied provenance candidates. Present measurements must be witnessed 0..1 packets; missing required measurements are typed UNKNOWN and routed to measurement_plan rather than rejected or coerced to zero. Selection is coverage-aware, budgeted, EQ.1-safe and replayable.","inputSchema":{"type":"object","required":["query_ref","query","candidates"],"properties":{"query_ref":{"type":"string","minLength":1},"query":QUERY_SCHEMA,"candidates":{"type":"array","items":CANDIDATE_SCHEMA},"equivalence_context":{"type":"string"},"eq_snapshot":{"type":"object"},"actor":{"type":"string"},"task":{"type":"string"},"persist":{"type":"boolean"}},"additionalProperties":False}},
{"name":"athena_retrieval_get","description":"Fetch one persisted RAGRUN receipt with exact query/candidate/EQ input, selected sources, coverage, solver/optimality and decision digest.","inputSchema":{"type":"object","required":["run_id"],"properties":{"run_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_retrieval_replay","description":"Recompile one stored RAGRUN from its exact frozen inputs and compare decision digest, selected sources, coverage and equivalence report.","inputSchema":{"type":"object","required":["run_id"],"properties":{"run_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_retrieval_recent","description":"List recent persisted RAGRUN receipts without expanding full candidate payloads.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer","minimum":1,"maximum":500}},"additionalProperties":False}},
]
RETRIEVAL_RESOURCE={"uri":"athena://retrieval","name":"RAG.1 Decision-Conditioned Retrieval Compiler","mimeType":"application/json"}