AUTHORITY_SYMBOLS=['?','+','!','#']
VERIFIED_REF_SCHEMA={'type':'object','required':['verified','ref'],'properties':{'verified':{'const':True},'ref':{'type':'string','minLength':1}},'additionalProperties':True}
EVIDENCE_SCHEMA={'type':'object','required':['kind','verified','ref'],'properties':{'kind':{'enum':['support','derive','reproduce']},'verified':{'const':True},'ref':{'type':'string','minLength':1}},'additionalProperties':True}
CANONICAL_AUTHORITY_SCHEMA={'type':'object','required':['authorized','ref'],'properties':{'authorized':{'const':True},'ref':{'type':'string','minLength':1}},'additionalProperties':True}
TEST_SCHEMA={'type':'object','required':['procedure','observation','result','witness'],'properties':{'procedure':{},'observation':{},'result':{},'witness':{'oneOf':[{'type':'string','minLength':1},VERIFIED_REF_SCHEMA]}},'additionalProperties':True}
AUTHORITY_TOOLS=[
 {'name':'athena_claim_register','description':"Register or reuse persistent claim authority head at Y='?'. Authority is distinct from confidence, truth, consensus, pheromone and reward.",'inputSchema':{'type':'object','required':['claim_id','source_ref'],'properties':{'claim_id':{'type':'string','minLength':1},'source_ref':{'type':'string','minLength':1},'actor':{'type':'string'}},'additionalProperties':False}},
 {'name':'athena_claim_state','description':'Read current typed authority state and witness history pointers for one claim.','inputSchema':{'type':'object','required':['claim_id'],'properties':{'claim_id':{'type':'string','minLength':1}},'additionalProperties':False}},
 {'name':'athena_claim_list','description':'List claim authority heads, optionally filtering by Y or challenge status.','inputSchema':{'type':'object','properties':{'y':{'enum':AUTHORITY_SYMBOLS},'status':{'enum':['ACTIVE','CHALLENGED','CANONICAL_CHALLENGED']},'limit':{'type':'integer','minimum':1,'maximum':500}},'additionalProperties':False}},
 {'name':'athena_claim_promote','description':'Advance exactly one authority step. ?->+ requires verified evidence; +->! witnessed execution; !-># explicit canonical authority.','inputSchema':{'type':'object','required':['claim_id','target_y'],'properties':{'claim_id':{'type':'string','minLength':1},'target_y':{'enum':AUTHORITY_SYMBOLS},'evidence':{'type':'array','items':EVIDENCE_SCHEMA},'test':TEST_SCHEMA,'canonical_authority':CANONICAL_AUTHORITY_SCHEMA,'actor':{'type':'string'}},'additionalProperties':False}},
 {'name':'athena_claim_challenge','description':'Record a material verified challenge. Noncanonical claims return to ?/CHALLENGED; canonical claims remain #/CANONICAL_CHALLENGED and block automatic routing.','inputSchema':{'type':'object','required':['claim_id','witness','reason'],'properties':{'claim_id':{'type':'string','minLength':1},'witness':VERIFIED_REF_SCHEMA,'reason':{'type':'string','minLength':1},'actor':{'type':'string'}},'additionalProperties':False}},
 {'name':'athena_claim_resolve_canonical_challenge','description':'Resolve CANONICAL_CHALLENGED through explicit authorized UPHOLD or DEMOTE governance.','inputSchema':{'type':'object','required':['claim_id','decision','authority'],'properties':{'claim_id':{'type':'string','minLength':1},'decision':{'enum':['UPHOLD','DEMOTE']},'authority':CANONICAL_AUTHORITY_SCHEMA,'actor':{'type':'string'}},'additionalProperties':False}},
]
AUTHORITY_TOOL_NAMES={tool['name'] for tool in AUTHORITY_TOOLS}
AUTHORITY_RESOURCE={'uri':'athena://authority','name':'Typed Claim Authority Registry Y1','mimeType':'application/json'}
