from __future__ import annotations

from .orchestration_hug import HUG_PARAMS

PARAM_SEMANTICS_SCHEMA={"type":"object","required":list(HUG_PARAMS),"properties":{p:{"oneOf":[{"type":"string","minLength":1},{"type":"object","required":["meaning"],"properties":{"meaning":{"type":"string","minLength":1}},"additionalProperties":True}]} for p in HUG_PARAMS},"additionalProperties":False}
ARGUMENT_SCHEMA={"type":"object","required":list(HUG_PARAMS),"properties":{p:{} for p in HUG_PARAMS},"additionalProperties":False}
VERIFIED_REF_SCHEMA={"type":"object","required":["verified","ref"],"properties":{"verified":{"const":True},"ref":{"type":"string","minLength":1}},"additionalProperties":True}
CANONICAL_REF_SCHEMA={"type":"object","required":["authorized","ref"],"properties":{"authorized":{"const":True},"ref":{"type":"string","minLength":1}},"additionalProperties":True}
TEST_PACKET_SCHEMA={"type":"object","required":["procedure","observation","result","witness"],"properties":{"procedure":{},"observation":{},"result":{},"witness":{"oneOf":[{"type":"string","minLength":1},VERIFIED_REF_SCHEMA]}},"additionalProperties":True}

HUG_TOOLS=[
{"name":"athena_hug_register","description":"Register an exact HUG implementation identity. All six parameter meanings io,au,fx,lm,er,st plus algorithm/code ref/digest and input/output schemas are mandatory. Registration creates CANDIDATE only; it does not assert the algorithm is tested/canonical.","inputSchema":{"type":"object","required":["name","version","algorithm_ref","implementation_digest","parameter_semantics","input_schema","output_schema"],"properties":{"name":{"type":"string","minLength":1},"version":{"type":"string","minLength":1},"algorithm_ref":{"type":"string","minLength":1},"implementation_digest":{"type":"string","minLength":1},"parameter_semantics":PARAM_SEMANTICS_SCHEMA,"input_schema":{"type":"object"},"output_schema":{"type":"object"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_state","description":"Return one registered HUG implementation state including exact six-parameter semantics, schemas, status, test packet and canonical witness route.","inputSchema":{"type":"object","required":["impl_id"],"properties":{"impl_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_list","description":"List registered HUG implementations, optionally filtered by CANDIDATE/TESTED/CANONICAL.","inputSchema":{"type":"object","properties":{"status":{"enum":["CANDIDATE","TESTED","CANONICAL"]},"limit":{"type":"integer","minimum":1,"maximum":500}},"additionalProperties":False}},
{"name":"athena_hug_promote","description":"Advance HUG implementation exactly one status step. CANDIDATE->TESTED requires procedure+observation+result+witness; TESTED->CANONICAL requires explicit authorized canonical ref. Skips are rejected.","inputSchema":{"type":"object","required":["impl_id","target_status"],"properties":{"impl_id":{"type":"string"},"target_status":{"enum":["CANDIDATE","TESTED","CANONICAL"]},"test":TEST_PACKET_SCHEMA,"canonical_authority":CANONICAL_REF_SCHEMA,"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_plan","description":"Create a HUGINV execution packet for a registered implementation. Requires exactly io,au,fx,lm,er,st, validates registered input schema, freezes implementation snapshot and input digest, and returns PLANNED only; it does not fake semantic execution.","inputSchema":{"type":"object","required":["impl_id","arguments"],"properties":{"impl_id":{"type":"string"},"arguments":ARGUMENT_SCHEMA,"context":{"type":"object"},"required_status":{"enum":["CANDIDATE","TESTED","CANONICAL"]},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_complete","description":"Complete a PLANNED HUGINV with output validated against the frozen implementation output schema and a verified execution receipt.","inputSchema":{"type":"object","required":["invocation_id","output","receipt"],"properties":{"invocation_id":{"type":"string"},"output":{},"receipt":VERIFIED_REF_SCHEMA,"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_fail","description":"Record a witnessed external/registered-executor failure for a PLANNED HUGINV without fabricating output.","inputSchema":{"type":"object","required":["invocation_id","reason","witness"],"properties":{"invocation_id":{"type":"string"},"reason":{"type":"string","minLength":1},"witness":VERIFIED_REF_SCHEMA,"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_invocation","description":"Fetch one HUGINV including frozen implementation snapshot, six arguments, context, status, output/receipt or failure.","inputSchema":{"type":"object","required":["invocation_id"],"properties":{"invocation_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hug_verify_packet","description":"Recompute the HUGINV packet digest. This verifies frozen implementation/input integrity only; semantic algorithm replay remains N/A unless a real registered executor replays it.","inputSchema":{"type":"object","required":["invocation_id"],"properties":{"invocation_id":{"type":"string"}},"additionalProperties":False}},
]
HUG_RESOURCE={"uri":"athena://hug","name":"Fail-Closed HUG Algorithm ABI / Implementation Registry","mimeType":"application/json"}
