PROTOCOL_VERSION="2025-11-25"
SERVER_INFO={"name":"athena-canonical-mcp","version":"2.4.0","description":"Canonical KC144/JSPACE/SCALE/AOR developmental control substrate with executable transforms and verified emissions"}

CANDIDATE_SCHEMA={"type":"object","properties":{"id":{"type":"string"},"oid":{"type":"string"},"cid":{"type":"string"},"name":{"type":"string"},"ref":{"type":"string"},"resolved":{"type":"boolean"},"requires":{"type":"array","items":{"type":"string"}},"readiness":{"type":"number"},"gain":{"type":"number"},"independence":{"type":"number"},"bridge":{"type":"number"},"cost":{"type":"number"},"delta_j":{"type":"number"},"information_gain":{"type":"number"},"option_value":{"type":"number"},"evidence":{"type":"number"},"connection":{"type":"number"},"replay":{"type":"number"},"navigation":{"type":"number"},"reconstruction":{"type":"number"},"implementation":{"type":"number"},"novelty":{"type":"number"},"duplicate":{"type":["number","boolean"]},"fake":{"type":["number","boolean"]},"bloat":{"type":"number"},"unsupported":{"type":["number","boolean"]},"unhandled_contradiction":{"type":["number","boolean"]},"coordinate_loss":{"type":"number"},"test":{"type":"object"},"transaction":{"type":"object"},"coordinates":{"type":"object"},"require_coordinates":{"type":"boolean"}},"additionalProperties":True}
RESIDUAL_SCHEMA={"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"severity":{"type":"number"},"leverage":{"type":"number"},"information_gain":{"type":"number"},"cost":{"type":"number"}},"additionalProperties":True}

TOOLS=[
{"name":"athena_register","description":"Create or reuse one canonical capability identity from a functional signature.","inputSchema":{"type":"object","required":["kind","domain","verb","object_name","method","input_contract","output_contract"],"properties":{"kind":{"type":"string"},"domain":{"type":"string"},"verb":{"type":"string"},"object_name":{"type":"string"},"method":{"type":"string"},"input_contract":{},"output_contract":{},"constraints":{"type":"object"},"payload":{},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_resolve","description":"Resolve a canonical OID/CID/name and return exact navigation, versions, graph edges and KC144 station.","inputSchema":{"type":"object","required":["identifier"],"properties":{"identifier":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_search","description":"Search canonical registry by semantic/canonical text.","inputSchema":{"type":"object","required":["query"],"properties":{"query":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":False}},
{"name":"athena_commit_delta","description":"Conditional object mutation. Rejects stale expected VID instead of creating a shadow mutation.","inputSchema":{"type":"object","required":["oid","expected_vid","delta"],"properties":{"oid":{"type":"string"},"expected_vid":{"type":["string","null"]},"delta":{},"actor":{"type":"string"},"status":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_ingest_text","description":"Persist a text manifestation and assign exact KC144/OID/VID/MID/paragraph/sentence/token/character coordinates to every non-whitespace lexeme.","inputSchema":{"type":"object","required":["oid","expected_vid","text","native_locator"],"properties":{"oid":{"type":"string"},"expected_vid":{"type":["string","null"]},"text":{"type":"string"},"native_locator":{"type":"string"},"carrier":{"type":"string"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_add_edge","description":"Add one typed JSPACE edge with provenance event.","inputSchema":{"type":"object","required":["src","relation","dst"],"properties":{"src":{"type":"string"},"relation":{"type":"string"},"dst":{"type":"string"},"attrs":{"type":"object"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_emit_agent_event","description":"Emit public liminal telemetry for an agent task; private chain-of-thought is neither requested nor stored.","inputSchema":{"type":"object","required":["agent","task","seq","intent","action","status"],"properties":{"agent":{"type":"string"},"task":{"type":"string"},"seq":{"type":"integer"},"intent":{"type":"string"},"action":{"type":"string"},"status":{"type":"string"},"progress":{"type":"number"},"pressure":{"type":"number"},"uncertainty":{"type":"number"},"needs":{"type":"array","items":{"type":"string"}},"offers":{"type":"array","items":{"type":"string"}},"blockers":{"type":"array","items":{"type":"string"}},"capability_delta":{"type":"array","items":{"type":"string"}},"coordinates":{"type":"object"},"residual":{},"frontier":{},"reward":{},"witnesses":{"type":"array"},"next":{},"return_ref":{"type":"string"}},"additionalProperties":True}},
{"name":"athena_match_help","description":"Match an agent's latest needs/blockers against peers' latest offers/capability deltas.","inputSchema":{"type":"object","required":["agent"],"properties":{"agent":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":50}},"additionalProperties":False}},
{"name":"athena_form_simplex","description":"Represent n-way coordination as a lazy (n-1)-simplex without materializing its exponential face lattice.","inputSchema":{"type":"object","required":["participants","task","topic"],"properties":{"participants":{"type":"array","items":{"type":"string"},"minItems":2,"maxItems":60},"task":{"type":"string"},"topic":{"type":"string"},"packet_refs":{"type":"array","items":{"type":"string"}}},"additionalProperties":False}},
{"name":"athena_promote_mutation","description":"Register a discovered mutation; global classes require adoption by all active agents next cycle.","inputSchema":{"type":"object","required":["mutation_class","payload","source_eid"],"properties":{"mutation_class":{"type":"string"},"payload":{},"source_eid":{"type":"string"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_pending_mutations","description":"Return globally visible mutations this agent has not adopted.","inputSchema":{"type":"object","required":["agent"],"properties":{"agent":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_adopt_mutation","description":"Record actual adoption of a global mutation by an agent, distinct from mere delivery/visibility.","inputSchema":{"type":"object","required":["agent","mutation_id"],"properties":{"agent":{"type":"string"},"mutation_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_hydrate","description":"Hydrate current canonical organism state: head, registry, recent causal history, JSPACE summary, SCALE and pending global mutations.","inputSchema":{"type":"object","properties":{"agent":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_orchestrate","description":"Compile and optionally persist an AOR.3 packet. UNKNOWN is never coerced to zero; incomplete formulas route to measurement. Dependencies and promotion gates must pass before automatic selection; Pareto alternatives and decision explanations remain visible.","inputSchema":{"type":"object","required":["seed"],"properties":{"seed":{},"candidates":{"type":"array","items":CANDIDATE_SCHEMA},"residuals":{"type":"array","items":RESIDUAL_SCHEMA},"budget":{"type":"object"},"actor":{"type":"string"},"task":{"type":"string"},"session_id":{"type":["string","null"]},"persist":{"type":"boolean"}},"additionalProperties":False}},
{"name":"athena_orchestration_get","description":"Fetch one persisted AORRUN receipt with exact input, output, decision digest and causal EID.","inputSchema":{"type":"object","required":["run_id"],"properties":{"run_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_orchestration_replay","description":"Recompute a persisted AORRUN from stored inputs and verify decision digest, next, grow and Pareto route.","inputSchema":{"type":"object","required":["run_id"],"properties":{"run_id":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_session_start","description":"Begin an agent session against the exact current semantic and Git heads; returns hydration state.","inputSchema":{"type":"object","required":["agent","task"],"properties":{"agent":{"type":"string"},"task":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_session_end","description":"Close a session with public summary telemetry and optionally checkpoint it into the configured canonical Git brain using expected-head CAS.","inputSchema":{"type":"object","required":["session_id","summary"],"properties":{"session_id":{"type":"string"},"summary":{"type":"object"},"expected_git_head":{"type":["string","null"]},"checkpoint_git":{"type":"boolean"}},"additionalProperties":False}},
{"name":"athena_git_status","description":"Return configured canonical Git brain root, branch, head and dirty state.","inputSchema":{"type":"object","additionalProperties":False}},
{"name":"athena_add_hyperedge","description":"Add one typed JSPACE hyperedge / n-way semantic relation with provenance.","inputSchema":{"type":"object","required":["relation","members"],"properties":{"relation":{"type":"string"},"members":{"type":"array","items":{"type":"string"},"minItems":2,"maxItems":60},"attrs":{"type":"object"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_crystallize_output","description":"Compile one visible output into a complete ATHENA crystal: identity/version/manifestation, exact lexeme coordinates, KC144, JSPACE, SCALE, lineage/time/liminal coordinates, open-world polyatlas, math objects, graph/hypergraph deltas and RETURN.","inputSchema":{"type":"object","required":["semantic","text","native_locator","agent","task","seq"],"properties":{"semantic":{"type":"object"},"text":{"type":"string"},"native_locator":{"type":"string"},"agent":{"type":"string"},"task":{"type":"string"},"seq":{"type":"integer"},"expected_vid":{"type":["string","null"]},"carrier":{"type":"string"},"edges":{"type":"array","items":{"type":"object"}},"hyperedges":{"type":"array","items":{"type":"object"}},"math_objects":{"type":"array","items":{"type":"object"}},"coordinates":{"type":"object"},"cut_lm":{"type":"object"},"evidence":{"type":"object"},"scale_promotions":{"type":"array","items":{"type":"string"}},"session_id":{"type":["string","null"]},"ephemeris":{"type":"object"},"status":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_dense_navigate","description":"Resolve an OID/CID/name/CRYS identifier through identity, version lineage, manifestations, all coordinate charts, JSPACE edges/hyperedges, math objects, crystal versions and RETURN routes.","inputSchema":{"type":"object","required":["identifier"],"properties":{"identifier":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_register_transform","description":"Register a typed coordinate transform T_ij:C_i->C_j. LOOKUP is navigational only; derivational modes require a safe declarative program and explicit comparison metric.","inputSchema":{"type":"object","required":["src_chart","dst_chart"],"properties":{"src_chart":{"type":"string"},"dst_chart":{"type":"string"},"operator_oid":{"type":["string","null"]},"operator_vid":{"type":["string","null"]},"status":{"type":"string"},"loss_model":{"type":"object"},"mode":{"type":"string"},"program":{"type":"object"},"metric":{"type":"object"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_coordinate_matrix","description":"Return the full chart-to-chart transform matrix, resolved coordinate subset, transform coverage, closed transform triangles and holonomy observations for an optional subject.","inputSchema":{"type":"object","properties":{"subject_id":{"type":["string","null"]}},"additionalProperties":False}},
{"name":"athena_record_holonomy","description":"Persist a measured closed coordinate-loop observation H_gamma with start, returned state, defect, metric and provenance event.","inputSchema":{"type":"object","required":["subject_id","route","start","returned","defect"],"properties":{"subject_id":{"type":"string"},"route":{"type":"array","items":{"type":"string"},"minItems":3},"start":{},"returned":{},"defect":{},"metric":{"type":["number","null"]},"status":{"type":"string"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_graph_path","description":"Compute a shortest directed JSPACE path between two nodes, optionally restricted to typed relations.","inputSchema":{"type":"object","required":["src","dst"],"properties":{"src":{"type":"string"},"dst":{"type":"string"},"relations":{"type":"array","items":{"type":"string"}},"max_depth":{"type":"integer","minimum":1,"maximum":64}},"additionalProperties":False}},
{"name":"athena_benchmark","description":"Return live substrate counts, AOR replay determinism sample and head state for regression/telemetry.","inputSchema":{"type":"object","additionalProperties":False}},
]

TOOLS += [
{"name":"athena_apply_transform","description":"Execute the newest registered T_ij for a subject using LOOKUP or the safe declarative transform DSL; compare against an independently resolved target when available and optionally persist a derived coordinate.","inputSchema":{"type":"object","required":["subject_id","src_chart","dst_chart"],"properties":{"subject_id":{"type":"string"},"src_chart":{"type":"string"},"dst_chart":{"type":"string"},"source_value":{},"persist":{"type":"boolean"},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_apply_transform_route","description":"Compose and execute a coordinate route C_i0->...->C_ik. Closed routes automatically measure holonomy only when every edge is derivational; LOOKUP-containing loops are marked N/A rather than falsely promoted.","inputSchema":{"type":"object","required":["subject_id","route"],"properties":{"subject_id":{"type":"string"},"route":{"type":"array","items":{"type":"string"},"minItems":2},"source_value":{},"actor":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_finalize_output","description":"Mandatory emission gateway for Athena-aware clients: crystallize the exact body, derive a header, assemble HEADER+BODY, create a third emission MID over the exact visible bytes, coordinate-index every visible lexeme, and return an ENV envelope.","inputSchema":{"type":"object","required":["semantic","text","native_locator","agent","task","seq"],"properties":{"semantic":{"type":"object"},"text":{"type":"string"},"native_locator":{"type":"string"},"agent":{"type":"string"},"task":{"type":"string"},"seq":{"type":"integer"},"expected_vid":{"type":["string","null"]},"carrier":{"type":"string"},"edges":{"type":"array","items":{"type":"object"}},"hyperedges":{"type":"array","items":{"type":"object"}},"math_objects":{"type":"array","items":{"type":"object"}},"coordinates":{"type":"object"},"cut_lm":{"type":"object"},"evidence":{"type":"object"},"scale_promotions":{"type":"array","items":{"type":"string"}},"session_id":{"type":["string","null"]},"ephemeris":{"type":"object"},"status":{"type":"string"}},"additionalProperties":False}},
{"name":"athena_verify_emission","description":"Verify an ENV emission by recomputing the exact visible-byte SHA-256; detects any post-crystallization mutation of the user-visible output.","inputSchema":{"type":"object","required":["envelope_id"],"properties":{"envelope_id":{"type":"string"},"visible_text":{"type":"string"}},"additionalProperties":False}},
]

PROMPTS=[{"name":"athena_maxdev","title":"ATHENA MAXDEV","description":"Whole-system AOR/MAXDEV cycle with uncertainty-safe frontier compilation, replay receipts, executable transforms, verified emissions and global diffusion.","arguments":[{"name":"task","required":True},{"name":"agent","required":False}]}]
