"""Validate the MYTHOS OS module registry, export the spec JSON and render the generated docs.

    python -m scripts.mythos_report            # validate, export, render
    python -m scripts.mythos_report --check    # verify the JSON export is in sync (no writes)

Direction of truth: ``athena_mcp/mythos_modules/*.py`` → ``spec/MYTHOS_OS_V1.json`` → ``docs/mythos_os/0[2-6]_*.md``.
"""
from __future__ import annotations

import json
import os
import sys
from collections import Counter
from typing import Any, Dict, List

from athena_mcp.mythos_kernel import MythosVM, atlas, benchmark, isomorphism_classes, bridge, service_matrix, signature_of, validate_modules
from athena_mcp.mythos_modules import MODULES
from athena_mcp.mythos_protocol import FAMILIES, GRADES, LAWS, MYTHOS_KERNEL_ABI, MYTHOS_VERSION, SERVICES
from athena_mcp.mythos_surface import ATHENA_ORGAN_MAP, kernel_abi

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "spec", "MYTHOS_OS_V1.json")
DOCS = os.path.join(ROOT, "docs", "mythos_os")
HEADER = "Generated by `python -m scripts.mythos_report`. Do not edit by hand.\n\n"


def spec_dict() -> Dict[str, Any]:
    return {"artifact": MYTHOS_VERSION, "abi": MYTHOS_KERNEL_ABI, "kernel": kernel_abi(), "athena_organ_map": ATHENA_ORGAN_MAP,
            "module_count": len(MODULES), "modules": MODULES, "laws": list(LAWS),
            "authority": "UNIFIED_DESCRIPTIVE_KERNEL_ONLY; SIMULATION != EXECUTION; ISOMORPHISM != IDENTITY"}


def export_json(path: str = JSON_PATH) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(spec_dict(), fh, ensure_ascii=False, indent=1)
        fh.write("\n")


def check_json(path: str = JSON_PATH) -> bool:
    with open(path, encoding="utf-8") as fh:
        on_disk = json.load(fh)
    return json.dumps(on_disk, sort_keys=True, ensure_ascii=False) == json.dumps(spec_dict(), sort_keys=True, ensure_ascii=False)


def _cell(x: Any) -> str:
    return str(x).replace("|", "\\|").replace("\n", " ")


# ------------------------------------------------------------------ renderers
def render_modules() -> str:
    out = ["# 02 · Module catalogue\n", HEADER]
    out.append(f"{len(MODULES)} modules · {len(FAMILIES)} families · {len(SERVICES)} services per module.\n\n")
    grade_totals = Counter(m["services"][s]["grade"] for m in MODULES for s in SERVICES)
    out.append("| grade | slots |\n|---|---|\n")
    for g in GRADES:
        out.append(f"| {g} | {grade_totals.get(g, 0)} |\n")
    out.append("\n")
    for fam in FAMILIES:
        mods = [m for m in MODULES if m["family"] == fam]
        if not mods:
            continue
        out.append(f"## {fam} ({len(mods)})\n\n")
        for m in mods:
            sig = signature_of(m)
            out.append(f"### `{m['id']}` — {_cell(m['name'])}\n\n")
            out.append(f"standing `{m['standing']}` · closure-grammar `{m.get('closure_grammar_id') or '—'}` · sources: {'; '.join(_cell(s) for s in m['sources'])}\n\n")
            if m.get("corpus_refs"):
                out.append(f"corpus: {', '.join(_cell(c) for c in m['corpus_refs'])} (🟠 only)\n\n")
            out.append("| service | grade | signature | summary |\n|---|---|---|---|\n")
            for s in SERVICES:
                slot = m["services"][s]
                out.append(f"| {s} | {slot['grade']} | `{_cell(sig[s])}` | {_cell(_summary(s, slot))} |\n")
            out.append("\n")
    return "".join(out)


def _summary(service: str, slot: Dict[str, Any]) -> str:  # noqa: C901
    if slot.get("absent"):
        return f"⊥ {slot.get('notes', '')}"
    if service == "BOOT":
        return " → ".join(st["stage"] for st in slot["stages"]) or slot["mode"]
    if service == "MEMMAP":
        return f"{slot['addressing']}; axis {slot.get('axis') or '—'}; " + ", ".join(f"{r['name']} ({r['level']})" for r in sorted(slot['realms'], key=lambda r: -r['level']))
    if service == "PROC":
        return f"{slot['scheduler']}; " + ", ".join(a["name"] for a in slot["agents"])
    if service == "CLOCK":
        return f"{slot['intercalation']['policy']}: {slot['intercalation'].get('rule') or ''}; periods " + ", ".join(f"{p['name']}={p['length']}" for p in slot["periods"])
    if service == "RITE":
        return "; ".join(f"{p['name']} [{' '.join(p['steps'])}]" for p in slot["protocols"])
    if service == "ORACLE":
        return "; ".join(f"{d['name']}: {d['entropy']} {d['encoding']} space {d['space']}" + (f", set aside {d['set_aside']}" if d.get('set_aside') else "") for d in slot["devices"])
    if service == "FAULT":
        return "; ".join(f"{f['name']} ({f['class']} → {f['outcome']})" for f in slot["faults"])
    if service == "LEDGER":
        return f"{slot['model']}; soul {', '.join(slot.get('soul') or [])}; → {' > '.join(slot.get('destinations') or [])}"
    if service == "RING":
        return " > ".join(f"{r['level']} {r['name']}" for r in sorted(slot["rings"], key=lambda r: r["level"]))
    if service == "CODEC":
        rec = slot["record"]
        return f"{rec['medium']} / {rec.get('script') or '—'} / base {rec.get('base') or '—'}; hull {slot.get('hull') or '—'}"
    if service == "CONST":
        return ", ".join(f"{c['n']} {c['role']} ({c['what']})" for c in slot["constants"])
    if service == "LAW":
        return f"canon {'closed' if slot['canon']['closed'] else 'open'}; " + "; ".join(slot["invariants"])
    return ""


def render_matrix() -> str:
    mat = service_matrix(MODULES)
    out = ["# 03 · Service matrix\n", HEADER,
           "Every module as twelve pattern tokens. Same token in a column = same structural class on that service (an isomorphism class, not an identity).\n\n"]
    out.append("| module | family | " + " | ".join(SERVICES) + " |\n|---|---|" + "---|" * len(SERVICES) + "\n")
    for r in mat["rows"]:
        out.append(f"| `{r['id']}` | {r['family']} | " + " | ".join(f"`{_cell(r['signature'][s])}` {r['grades'][s]}" for s in SERVICES) + " |\n")
    return "".join(out)


def render_atlas() -> str:
    a = atlas(MODULES)
    out = ["# 04 · KC144 atlas\n", HEADER,
           f"Rows = twelve families, columns = twelve services, `{a['law']}`. Each cell lists the modules in that family and the pattern histogram on that service. {a['boundary']}\n\n"]
    out.append("| | " + " | ".join(f"C{i:02d} {s}" for i, s in enumerate(SERVICES, start=1)) + " |\n|---|" + "---|" * len(SERVICES) + "\n")
    for ri, fam in enumerate(FAMILIES, start=1):
        row = [c for c in a["cells"] if c["row"] == ri]
        out.append(f"| **R{ri:02d} {fam}** | " + " | ".join(f"g{c['gid']}: {c['module_count']}" for c in row) + " |\n")
    out.append("\n## Cells\n\n")
    for c in a["cells"]:
        if not c["module_count"]:
            continue
        pats = "; ".join(f"`{_cell(k)}` ×{v}" for k, v in c["patterns"].items())
        out.append(f"- **{c['sid']}** R{c['row']:02d}C{c['col']:02d} {c['family']}/{c['service']} — {c['module_count']} module(s): {', '.join(c['modules'])} — {pats}\n")
    return "".join(out)


def render_runs() -> str:
    out = ["# 05 · Boot logs and VM traces\n", HEADER,
           "For every module: the boot log, one clock tick of a year (or sixteen steps), the first rite as a protocol trace, one seeded oracle draw, the first fault through its handlers, and one judgment. All output is symbolic simulation; nothing here executes, predicts, or authorises.\n\n"]
    for m in MODULES:
        vm = MythosVM(m)
        b = vm.boot(); t = vm.tick(365 if m["family"] != "ENGINEERED" else 16); i = vm.invoke(None, caller_ring=0)
        d = vm.divine(None, seed="athena"); f = vm.raise_fault(None); j = vm.judge(0.5); s = vm.spawn(); mm = vm.memmap()
        out.append(f"## `{m['id']}` — {_cell(m['name'])}\n\n")
        out.append(f"**BOOT** `{b['status']}` mode {b.get('mode')} · fault position {b.get('fault_position')} · reboots {b.get('reboots')}\n\n")
        if b.get("log"):
            out.append("```\n" + "\n".join(f"[{l['pc']:02d}] {l['stage']:<11} {l['event']}" for l in b["log"]) + "\n```\n\n")
        if mm["status"] == "MAPPED":
            out.append(f"**MEMMAP** {mm['addressing']} depth {mm['depth']} · " + " · ".join(f"{r['name']}@{r['level']}" for r in mm["table"]) + "\n\n")
        if s["status"] == "SPAWNED":
            out.append(f"**PROC** {s['scheduler']} · {s['process_count']} processes · roots {', '.join(s['roots'])}\n\n")
        if t["status"] == "TICKED":
            per = "; ".join(f"{p['name']}: {p['rollovers']} rollover(s), phase {p['phase_fraction']}" for p in t["periods"])
            out.append(f"**CLOCK** tick {t['days']}: {per}; intercalation {t['intercalation']['policy']} (due {t['intercalation']['intercalations_due']}, residue {t['intercalation']['accumulated_residue_days']})\n\n")
        if i["status"].startswith("SIMULATED"):
            out.append(f"**RITE** `{_cell(i['rite'])}` ring {i['required_ring']} · {' '.join(i['steps'])} · lint {'ok' if i['lint']['well_formed'] else i['lint']['violations']}\n\n")
        elif i["status"] != "SERVICE_ABSENT":
            out.append(f"**RITE** {i['status']}\n\n")
        if d["status"] == "SYMBOLIC_ONLY":
            out.append(f"**ORACLE** `{_cell(d['device'])}` {d['entropy']} {d['encoding']} space {d['sample_space']} ({d['entropy_bits']} bits) · seed athena → index {d['R_sampler']['index']} digits `{d['W_witness']['digits']}` · decoder {_cell(d['D_decoder']['name'])}\n\n")
        elif d["status"] != "SERVICE_ABSENT":
            out.append(f"**ORACLE** {d['status']}\n\n")
        if f["status"] in {"HANDLED", "UNHANDLED"}:
            out.append(f"**FAULT** `{_cell(f['fault'])}` {f['fault_class']} → {' → '.join(f['handler_chain'])} → **{f['outcome']}**\n\n")
        if j["status"] == "JUDGED":
            out.append(f"**LEDGER** {j['model']} score 0.5 → {_cell(j['destination'])} (of {' > '.join(j['destinations'])})\n\n")
    return "".join(out)


def render_unification() -> str:
    out = ["# 06 · Unification (generated part)\n", HEADER,
           "Isomorphism classes per service: modules whose pattern token coincides. A class is a structural fact about the encoding, never a claim that the traditions are the same (`STRUCTURAL_ISOMORPHISM != CULTURAL_IDENTITY`). The prose analysis is in 06_UNIFICATION_ANALYSIS.md.\n\n"]
    for s in SERVICES:
        classes = isomorphism_classes(MODULES, s)
        out.append(f"## {s}\n\n| signature | size | modules |\n|---|---|---|\n")
        for c in classes:
            out.append(f"| `{_cell(c['signature'])}` | {c['size']} | {', '.join(c['modules'])} |\n")
        out.append("\n")
    if "athena" in {m["id"] for m in MODULES}:
        by = {m["id"]: m for m in MODULES}
        out.append("## Bridges from the ATHENA self-module\n\nStrata verdict for a whole-signature bridge from `athena` to every other module. Every verdict is `BRIDGE_ALLOWED_WITH_LOSS` or a HOLD; none is an equivalence.\n\n| module | shared tokens | strata status |\n|---|---|---|\n")
        for m in MODULES:
            if m["id"] == "athena":
                continue
            br = bridge(by["athena"], m)
            out.append(f"| `{m['id']}` | {len(br['shared_tokens'])} | {br['strata']['status']} |\n")
    return "".join(out)


def render_all() -> None:
    os.makedirs(DOCS, exist_ok=True)
    for name, fn in (("02_MODULES.md", render_modules), ("03_SERVICE_MATRIX.md", render_matrix), ("04_KC144_ATLAS.md", render_atlas),
                     ("05_BOOT_LOGS.md", render_runs), ("06_UNIFICATION.md", render_unification)):
        with open(os.path.join(DOCS, name), "w", encoding="utf-8") as fh:
            fh.write(fn())


def main(argv: List[str]) -> int:
    errors = validate_modules(MODULES)
    if errors:
        print(f"{len(errors)} schema violation(s):", file=sys.stderr)
        for e in errors:
            print("  " + e, file=sys.stderr)
        return 2
    if "--check" in argv:
        ok = check_json()
        print("spec/MYTHOS_OS_V1.json", "in sync" if ok else "OUT OF SYNC")
        return 0 if ok else 1
    export_json()
    render_all()
    b = benchmark(MODULES)
    print(f"{len(MODULES)} modules validated; exported {os.path.relpath(JSON_PATH, ROOT)}; rendered docs; gates {b['gates_passed']}/{b['gate_count']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
